// import { Poppins, Open_Sans } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/Navbar/Navbar";
// import Footer from "../components/Footer/Footer";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
// });

// const openSans = Open_Sans({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800"],
//   variable: "--font-open-sans",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={poppins.className}>
//       <body className={`${openSans.variable} antialiased`}>


      
//         <Navbar />
    
        
//         {children}

//         <footer>
//           <Footer />
//         </footer>
        
//       </body>
      
//     </html>
//   );
// }








"use client";

import { Poppins, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import { useEffect, useRef, useState } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-open-sans",
});

// export const metadata = {
//   title: "Mirage Works",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const navRef = useRef(null);
  const [navHeight, setNavHeight] = useState(0);

  useEffect(() => {
    const updateHeight = () => {
      if (navRef.current) {
        setNavHeight(navRef.current.offsetHeight);
      }
    };

    updateHeight();
    window.addEventListener("resize", updateHeight);

    return () => window.removeEventListener("resize", updateHeight);
  }, []);

  return (
    <html lang="en" className={poppins.className}>
      <body className={`${openSans.variable} antialiased`}>
        
        {/* Navbar */}
        <Navbar ref={navRef} />

        {/* ✅ PROFESSIONAL FIX */}
        <main style={{ paddingTop: navHeight }}>
          {children}
        </main>

        {/* Footer */}
        <footer>
          <Footer />
        </footer>
        
      </body>
    </html>
  );
}
