export const DataBlogsSection = [
  {
    id: 1,
    image: '/logo/blog1.png',
    tag: 'Blog',
    date: 'April 16, 2026',
    title: 'The Future of ERP: Trends to Watch in 2026',
    description: 'Explore the upcoming trends in ERP systems for 2024 and how they can benefit your business operations.',
    buttonText: 'Read More',
    link:"/blogs",
  },
  {
    id: 2,
    image: '/logo/blog3.png',
    tag: 'Blog',
    date: 'May 03, 2026',
    title: 'Leveraging AI for Smarter Operations',
    description: 'Discover how artificial intelligence is transforming ERP and driving operational excellence.',
    buttonText: 'Read More',
    link:"/blogs",
  },
  {
    id: 3,
    image: '/logo/blog1.png',
    tag: 'Blog',
    date: 'June 12, 2026',
    title: 'Seamless ERP Integration for Modern Businesses',
    description: 'Learn how ERP integration can streamline your workflows and improve collaboration.',
    buttonText: 'Read More',
    link:"/blogs",
  },
  {
    id: 4,
    image: '/logo/blog3.png',
    tag: 'Blog',
    date: 'July 08, 2026',
    title: 'The Future of ERP: Trends to Watch in 2026',
    description: 'Explore the upcoming trends in ERP systems for 2024 and how they can benefit your business operations.',
    buttonText: 'Read More',
    link:"/blogs",
  },
  {
    id: 5,
    image: '/logo/blog1.png',
    tag: 'Blog',
    date: 'August 21, 2026',
    title: 'Leveraging AI for Performance',
    description: 'Strategic use of AI and machine learning to enhance performance and productivity.',
    buttonText: 'Read More',
    link:"/blogs",
  },
  {
    id: 6,
    image: '/logo/blog3.png',
    tag: 'Blog',
    date: 'September 05, 2026',
    title: 'Integration ERP: Connecting Your Business',
    description: 'How to achieve seamless integration between ERP systems and other business tools.',
    buttonText: 'Read More',
    link:"/blogs",
  }
];
